[package]
name = "sound-programming-practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cpal = "0.14"
dasp = {version = "0.11", features = ["all"]}
